/*

Project Euler - Problem 2 (from https://projecteuler.net/)
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.

*/


// Proposed solution
function evenFibonacci(limit) {
    var sum = 0,
        prev = 0,
        cur = 1,
        i,
        aux;
    i = 1;
    while(cur < limit){
        aux = prev;
        prev = cur;
        cur += aux;
        if(cur % 2 === 0)
            sum += cur;
        i++;
    }
    return sum;
}


// Testing the solution
console.log(evenFibonacci(4000000));

