#	Project Euler - Problem 2 (from https://projecteuler.net/)
#	Even Fibonacci numbers

#	Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#	By starting with 1 and 2, the first 10 terms will be:

#	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#	By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
#	find the sum of the even-valued terms.

#	Proposed solution
def evenFibonacci limit
    serie = [1]
	serie = serie.inject(serie) do |ar, elem| 
		prev = (ar[-2] != nil ? ar[-2] : 1)
		ar << prev + elem if (elem + prev) <= limit
		ar
	end
	return serie.inject(0) {|sum, elem| elem % 2 == 0 ? sum + elem : sum}
end


#	Testing the solution
puts "The sum of the even-valued terms is: #{evenFibonacci 4000000}"

